### PR TITLE
Change to GALAXY_CONFIG_FTP_UPLOAD_SITE

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by drosofff** [comment]
I think there is still a problem because now I am testing on a fresh instance an install from scratch and I have 
```
imac-chris:ansible-artimed aligre$ ansible-playbook --inventory-file=hosts galaxy.yml
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : include] *********************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-os/tasks/system_users.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-os : Add system groups] ***********************
ok: [52.91.147.12] => (item={u'gid': 1450, u'name': u'galaxy'})
ok: [52.91.147.12] => (item={u'gid': 1550, u'name': u'postgres'})

TASK [galaxyprojectdotorg.galaxy-os : Add shadow groups] ***********************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add postgres user] ***********************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Adjust postgresql permissions] ***********
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add galaxy user] *************************
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add nobody user to shadow group] *********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : include] *********************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-os/tasks/packages.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-os : Add custom Galaxy PPA (used for nginx package)] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add custom Galaxy PPA (used for nginx package)] ***
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add Docker repository key] ***************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add Docker repository] *******************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Update APT cache] ************************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Install required system packages] ********
ok: [52.91.147.12] => (item=[u'ant', u'cmake', u'curl', u'g++', u'gcc', u'gfortran', u'git-core', u'libffi-dev', u'liblapack-dev', u'libncurses5-dev', u'libopenblas-dev', u'libpam0g-dev', u'libpq-dev', u'libsparsehash-dev', u'make', u'mercurial', u'nginx-extras', u'openssh-server', u'patch', u'pkg-config', u'postgresql', u'postgresql', u'postgresql-client', u'python-boto', u'python-dev', u'python-prettytable', u'python-psycopg2', u'python-virtualenv', u'python-pip', u'rsync', u'slurm-drmaa-dev', u'supervisor', u'swig', u'sysstat', u'unzip', u'wget', u'zlib1g-dev'])

TASK [galaxyprojectdotorg.galaxy-os : Install packages for system maintenance] *
skipping: [52.91.147.12] => (item=[]) 

TASK [galaxyprojectdotorg.galaxy-os : Install required system packages - release_specific] ***
ok: [52.91.147.12] => (item=[u'postgresql-plpython-9.3', u'postgresql-server-dev-9.3'])

TASK [galaxyprojectdotorg.galaxy-os : Install required system packages - 15.10] 
skipping: [52.91.147.12] => (item=[]) 

TASK [galaxyprojectdotorg.galaxy-os : include] *********************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-os/tasks/docker.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-os : Install Docker package] ******************
ok: [52.91.147.12] => (item=[u'docker-engine'])

TASK [galaxyprojectdotorg.galaxy-os : Install apparmor] ************************
skipping: [52.91.147.12] => (item=[]) 

TASK [galaxyprojectdotorg.galaxy-os : Allow galaxy user to run docker with sudo] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Add Galaxy user to docker group - allowing sudoless docker usage] ***
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-os : Set DOCKER_OPTS] *************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : service] ******************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : supervisorctl] ************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : supervisorctl] ************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : service] ******************************************
skipping: [52.91.147.12]

TASK [ensure_postgresql_up : command] ******************************************
changed: [52.91.147.12]

TASK [ensure_postgresql_up : discover location of pg_data] *********************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : discover postgres version] ************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : set_fact] *****************************************
ok: [52.91.147.12]

TASK [natefoo.postgresql_objects : Revoke extra privileges] ********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_privileges}}'). This
 feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [natefoo.postgresql_objects : Drop databases] *****************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_databases}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [52.91.147.12] => (item={u'owner': u'galaxy', u'name': u'galaxy'}) 

TASK [natefoo.postgresql_objects : Create and drop users] **********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_users}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [52.91.147.12] => (item={u'password': u'galaxy', u'name': u'galaxy'})

TASK [natefoo.postgresql_objects : Create groups] ******************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_groups}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [natefoo.postgresql_objects : Add or remove users from groups] ************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_groups}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [natefoo.postgresql_objects : Drop groups] ********************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_groups}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [natefoo.postgresql_objects : Create databases] ***************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_databases}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [52.91.147.12] => (item={u'owner': u'galaxy', u'name': u'galaxy'})

TASK [natefoo.postgresql_objects : Grant user database privileges] *************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_users}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [52.91.147.12] => (item={u'password': u'galaxy', u'name': u'galaxy'}) 

TASK [natefoo.postgresql_objects : Grant extra privileges] *********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_objects_privileges}}'). This
 feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/clone.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Check for Galaxy] ***************************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Get current Galaxy changeset (hg)] **********
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Get current Galaxy commit id (git)] *********
ok: [52.91.147.12]
 [WARNING]: Consider using git module rather than running git


TASK [galaxyprojectdotorg.galaxy : Report current Galaxy changeset] ************
ok: [52.91.147.12] => {
    "msg": "Current changeset of /home/galaxy/galaxy 9e980862c8b763cf3dd0209be49f0d2d75a90614 does not match playbook version release_16.01"
}

TASK [galaxyprojectdotorg.galaxy : Update Galaxy to correct changeset (hg)] ****
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Update Galaxy to correct changeset (git)] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/virtualenv.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Create Galaxy virtualenv] *******************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Remove orphaned .pyc files and compile bytecode] ***
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : include] ************************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/static_setup.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Create Galaxy config dir] *******************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Install additional Galaxy config files (static)] ***
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{galaxy_config_files}}'). This feature 
will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [galaxyprojectdotorg.galaxy : Install additional Galaxy config files (template)] ***
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{galaxy_config_templates}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [galaxyprojectdotorg.galaxy : Create Galaxy configuration file] ***********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/dependencies.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Check if Galaxy uses eggs or wheels] ********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Fetch Galaxy eggs] **************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Install Galaxy pip] *************************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Create binary-compatibility.cfg if necessary] ***
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Install Galaxy base dependencies] ***********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Collect Galaxy conditional dependency requirement strings] ***
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Install Galaxy conditional dependencies] ****
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax 
('{{conditional_dependencies.stdout_lines}}'). This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ok: [52.91.147.12] => (item=psycopg2==2.6.1)
ok: [52.91.147.12] => (item=drmaa)

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/mutable_setup.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Create mutable configuration file directory] 
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Instantiate mutable configuration files] ****
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{galaxy_mutable_configs}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/config/shed_tool_conf.xml', u'src': u'/home/galaxy/galaxy/config/shed_tool_conf.xml.sample'})
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/config/migrated_tools_conf.xml', u'src': u'/home/galaxy/galaxy/config/migrated_tools_conf.xml.sample'})
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/config/shed_data_manager_conf.xml', u'src': u'/home/galaxy/galaxy/config/shed_data_manager_conf.xml.sample'})
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/config/shed_tool_data_table_conf.xml', u'src': u'/home/galaxy/galaxy/config/shed_tool_data_table_conf.xml.sample'})

TASK [galaxyprojectdotorg.galaxy : include] ************************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy/tasks/database.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy : Get current Galaxy DB version] **************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Get maximum Galaxy DB version] **************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Create Galaxy DB] ***************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy : Upgrade Galaxy DB] **************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/galaxy_root.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Run common_startup.sh to create welcome.html from sample] ***
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Install watchdog for galaxy] *********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/galaxy_metrics.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Setup job metrics] *******************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/uwsgi.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install uwsgi for galaxy] ************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/nginx.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Create nginx configuration file] *****
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Create nginx upload_store dir] *******
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Create nginx uwsgi configuration] ****
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Create nginx Galaxy web configuration] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Create nginx IDE configuration] ******
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Add htpasswd file.] ******************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/proftpd.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install proftpd related system packages] ***
ok: [52.91.147.12] => (item=[u'proftpd', u'proftpd-mod-pgsql'])

TASK [galaxyprojectdotorg.galaxy-extras : Create Galaxy configuration file] ****
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Load Proftpd modules] ****************
ok: [52.91.147.12] => (item=LoadModule mod_sql.c)
ok: [52.91.147.12] => (item=LoadModule mod_sql_passwd.c)
ok: [52.91.147.12] => (item=LoadModule mod_sql_postgres.c)

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/slurm.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install pip] *************************
ok: [52.91.147.12] => (item=[u'python-pip'])

TASK [galaxyprojectdotorg.galaxy-extras : Install SLURM system packages] *******
ok: [52.91.147.12] => (item=[u'munge', u'slurm-llnl', u'slurm-drmaa-dev', u'python-psutil'])

TASK [galaxyprojectdotorg.galaxy-extras : Install SLURM system packages] *******
ok: [52.91.147.12] => (item=[u'slurm-llnl-torque'])

TASK [galaxyprojectdotorg.galaxy-extras : Install SLURM system packages] *******
skipping: [52.91.147.12] => (item=[]) 

TASK [galaxyprojectdotorg.galaxy-extras : Create Munge Key] ********************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Setup Munge permissions and folder] **
ok: [52.91.147.12] => (item=/var/run/munge)
ok: [52.91.147.12] => (item=/var/lib/munge)
ok: [52.91.147.12] => (item=/var/log/munge)
ok: [52.91.147.12] => (item=/var/run/munge)
ok: [52.91.147.12] => (item=/etc/munge)

TASK [galaxyprojectdotorg.galaxy-extras : Setup tmp area for slurm.] ***********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Create slurm configuration file] *****
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Check if Galaxy uses eggs or wheels] *
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Fetch DRMAA egg for Galaxy] **********
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Fetch DRMAA wheel for Galaxy] ********
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Install Galaxy job conf] *************
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/supervisor.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install web related system packages] *
ok: [52.91.147.12] => (item=[u'uwsgi', u'uwsgi-plugin-python', u'supervisor'])

TASK [galaxyprojectdotorg.galaxy-extras : Create Galaxy configuration file] ****
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Stop supervisor] *********************
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove uwsgi.] **************
changed: [52.91.147.12] => (item=uwsgi)

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove munge.] **************
ok: [52.91.147.12] => (item=munge)

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove slurm.] **************
ok: [52.91.147.12] => (item=slurm-llnl)

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove slurm.] **************
skipping: [52.91.147.12] => (item=slurmd) 
skipping: [52.91.147.12] => (item=slurmctld) 

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove postgresql.] *********
ok: [52.91.147.12] => (item=postgresql)

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove proftpd.] ************
ok: [52.91.147.12] => (item=proftpd)

TASK [galaxyprojectdotorg.galaxy-extras : Stop and remove nginx.] **************
ok: [52.91.147.12] => (item=nginx)

TASK [galaxyprojectdotorg.galaxy-extras : Start supervisor] ********************
changed: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
skipping: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/galaxy_scripts.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install repository intallation script.] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Install galaxy user creation script.] 
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Install export user files script.] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : include] *****************************
included: /Users/aligre/ansible-artimed/roles/galaxyprojectdotorg.galaxy-extras/tasks/startup.yml for 52.91.147.12

TASK [galaxyprojectdotorg.galaxy-extras : Install cgroupfs_mount.sh for startup script.] ***
ok: [52.91.147.12]

TASK [galaxyprojectdotorg.galaxy-extras : Install startup script used to configure container.] ***
ok: [52.91.147.12]

TASK [set_supervisor_env_vars : Add supervisor ENV vars] ***********************
ok: [52.91.147.12] => (item=export IP_ADDRESS=`curl icanhazip.com`)
ok: [52.91.147.12] => (item=export GALAXY_CONFIG_FTP_UPLOAD_SITE="ftp://$IP_ADDRESS")
ok: [52.91.147.12] => (item=export MASQUERADE_ADDRESS=$IP_ADDRESS)
ok: [52.91.147.12] => (item=export NATIVE_SPEC="--ntasks=`/usr/bin/nproc` --share")

TASK [ensure_postgresql_up : service] ******************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : supervisorctl] ************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : supervisorctl] ************************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : service] ******************************************
skipping: [52.91.147.12]

TASK [ensure_postgresql_up : command] ******************************************
changed: [52.91.147.12]

TASK [ensure_postgresql_up : discover location of pg_data] *********************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : discover postgres version] ************************
ok: [52.91.147.12]

TASK [ensure_postgresql_up : set_fact] *****************************************
ok: [52.91.147.12]

TASK [artimed_extras : include] ************************************************
included: /Users/aligre/ansible-artimed/roles/artimed_extras/tasks/galaxy_admin.yml for 52.91.147.12

TASK [artimed_extras : Create/invoke script virtualenv for create galaxy admin] 
ok: [52.91.147.12] => (item=pyyaml)
ok: [52.91.147.12] => (item=bioblend)

TASK [artimed_extras : Create Galaxy admin user] *******************************
changed: [52.91.147.12]

TASK [artimed_extras : include] ************************************************
included: /Users/aligre/ansible-artimed/roles/artimed_extras/tasks/extras.yml for 52.91.147.12

TASK [artimed_extras : Create proftpd dir] *************************************
ok: [52.91.147.12]

TASK [artimed_extras : Manage template for proftpd] ****************************
changed: [52.91.147.12] => (item={u'dest': u'/etc/proftpd/proftpd.conf', u'src': u'proftpd.conf.j2'})

TASK [artimed_extras : Create tool dependency dir] *****************************
ok: [52.91.147.12]

TASK [artimed_extras : Copy additional files] **********************************
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/static/', u'src': u'extra-files/metavisitor/welcome.html'})
ok: [52.91.147.12] => (item={u'dest': u'/home/galaxy/galaxy/static/images/', u'src': u'extra-files/metavisitor/metavisitor_logo.png'})

TASK [artimed_extras : Restart/start supervisor tasks] *************************
failed: [52.91.147.12] => (item={u'state': u'restarted', u'name': u'proftpd'}) => {"failed": true, "item": {"name": "proftpd", "state": "restarted"}, "msg": "proftpd: stopped\nproftpd: ERROR (abnormal termination)\n"}
ok: [52.91.147.12] => (item={u'state': u'started', u'name': u'munge'})
ok: [52.91.147.12] => (item={u'state': u'started', u'name': u'nginx'})
	to retry, use: --limit @galaxy.retry

PLAY RECAP *********************************************************************
52.91.147.12               : ok=116  changed=16   unreachable=0    failed=1   
```

**Comment by drosofff** [comment]
Retesting with clean master branch

**Comment by mvdbeek** [comment]
@drosofff I don't know if you know this, but if you look at the travis build, you can see how the docker build does a fresh installation (you have to click on the line that says `docker build ...`
screen shot 2016-04-23 at 20 33 35

Then if you scroll down you see:
```
TASK [artimed_extras : include] ************************************************
skipping: [localhost]
RUNNING HANDLER [galaxyprojectdotorg.galaxy : restart galaxy] ******************
ok: [localhost] => {
    "msg": "RESTARTER NOT IMPLEMENTED - Please restart Galaxy manually"
}
RUNNING HANDLER [galaxyprojectdotorg.galaxy : email administrator with changeset id] ***
skipping: [localhost]
PLAY RECAP *********************************************************************
localhost                  : ok=140  changed=79   unreachable=0    failed=0   
```

In fact the travis test would not succeed if ansible reports a failed check.
So the question is what caused this proftpd failed start :/
If you can keep this instance where this happens alive I'll have a look tomorrow / monday.

**Comment by drosofff** [comment]
I am afraid I will save by money.

Is it aws specific anyway ?

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-04-23 20:23 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
Nevermind, I didn't see #130 , if this happens reproducibly with aws instances thren we don't need this.
I thought this was specific to old instances. Can you post the excerpt about proftpd from `/etc/supervisor/conf.d/galaxy.conf` ?
Or alternatively, do you get any changes with `git submodule sync && git submodule update --recursive` in the ansible-artimed folder?

**Pull request merged**
