### PR TITLE
Persistent import postgres fix, data managers and dataset purge

### LINKED ISSUE #115: Data managers missing from metavisitor tool list
I guess those should be fasta and dbkey, bowtie and bowtie2.
Is there a blast data manager?

Ping @drosofff

### PR DESCRIPTION
**Pull request by mvdbeek**
- Persistent import postgres fix

- Include data managers for bowtie, bowtie2 and fasta in metavisitor tool list.
The order of the tools is slightly re-arranged (ordered alphabetically), because I used the get_tool_tool_yml_from_gi.py script on an instance where I manually installed those data managers.

- Allow users to delete files via UI

- Add ../shed_tools/ directory to list of directories that need to persist.

Closes #115 #116 #117 #118

### CODE REVIEW

**Comment by mvdbeek** [comment]
I have tested this on @drosofff's  instance on the IFB cloud. What was missing was the shed_tools directory. To "fix" your instance, I deleted the /export/exported_dirs.yml file (we use this to check if we should export or not) and ran the last command from the Dockerfile again:
```
ansible-playbook galaxy.yml -c local --tags "persists_galaxy,nginx_config,galaxy_config_files,galaxy_extras_job_conf" --skip-tags=skip_supervisor_start_in_docker \
           --extra-vars nginx_galaxy_location=$NGINX_GALAXY_LOCATION \
           --extra-vars galaxy_admin=$GALAXY_CONFIG_ADMIN_USERS -i docker_inventory
```
This caused the /home/galaxy/shed_tools directory to appear in /export/home/galaxy/shed_tools.
So if you shutdown this instance and start it again, you should have all the custom-installed tools still installed (but I didn't test it).

**Comment by drosofff** [comment]
There is progress... but the data manager and their tables which I manually installed on the instance when data were persisted are still missing.

**Comment by mvdbeek** [comment]
> but the data manager and their tables which I manually installed on the instance when data were persisted are still missing.

When did you install those ? After I added my last comment to this PR?

**Comment by mvdbeek** [comment]
OK, it was sufficient to re-install the data managers, then you get the reference data back automatically.
The shed_tools directory contains for example `shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bowtie2_index_builder/e87aeff2cf88/data_manager_bowtie2_index_builder`. With the command I posted above we were copying what was present in the image to the correct location, but that didn't include the manually installed tools (which were not present in `/export/home/galaxy/shed_tools/...`), so that's why your data managers were not present.

**Comment by drosofff** [comment]
👍 👍

**Pull request merged**
