### PR TITLE
Copy data to export directory, bind-mount back into source directory

### PR DESCRIPTION
**Pull request by mvdbeek**
This seems to validate at least the travis test suite, except for a test that was not present in galaxy's 15.10 release (`Method is not implemented`).
A manual test on the IFB (including reboot) was successful as well.
TODO:
 - ~~export postgresql data folder, additional folders (shed_tools, tool_deps, tool_data)~~
 - ~~mechanism for import on a new instance~~
 - test that confirms import/export really works -> docker?

### CODE REVIEW

**Comment by mvdbeek** [comment]
Alright, the import/export seems smooth now, we only need to make sure we also get postgresql and tool-data.

**Comment by mvdbeek** [comment]
OK, now everything should be working. This needs real-life testing now!

**Comment by fabiorjvieira** [comment]
@mvdbeek yesterday I passed the day testing the symlinks (running one workflow, history and installing tools). It seems to work. What is the next step? Merge this pull request? Use rsync instead of copy? Do another pull request?

**Comment by mvdbeek** [comment]
@fabiorjvieira where are your test results?
The advantage of bind-mounts is that the files are still there, you can mount back different export directories on to the same instance.
Also with symlnks you cannot re-run the playbook, since there are multiple instances of `file: path={{ whatever_path }} state=directory`

**Comment by mvdbeek** [comment]
@fabiorjvieira 
I'd encourage you to push your changes to the ARTbio symlinks branch, you'll get automatic testing.
It's nice to compare the solutions, maybe one is better than the other, but at least we have a trace of how this can be implemented in different ways.

**Comment by mvdbeek** [comment]
I'm merging this, since it has become quite the huge PR.
I did test the import/export, and it works as it does for galaxy-stable, except we need to pass --privileged due to the bind-mounts. Possibly this would work with real data containers.
The whole persistence needs automatic tests, but I'll work on that in a future PR

**Pull request merged**
